Add JSONPath + example for ConditionalInterceptor
membrane/api-gateway pull request #1268
Opened 2024-09-11 08:21 UTC by christiangoerdes

- Implement JSONPath functionality in BuiltInFunctions to evaluate expressions using JSON data.
- Add test cases for the new JSONPath function within BuiltInFunctionsTest.
- Introduce conditional logic in the API configuration to handle JSON requests based on specific criteria, using Spring Expression Language (SpEL).

2024-09-11 08:21 UTC, christiangoerdes commented
/ok-to-test

2024-09-23 09:50 UTC, rrayst commented
This branch is currently /not-ok-to-test .

Please merge the master branch into this branch (e.g. 'Update branch' above) and resolve the conflicts. Once completed, feel free to set /ok-to-test again.

2024-09-26 07:31 UTC, christiangoerdes commented
/ok-to-test

2024-09-27 08:54 UTC, predic8 requested changes

2024-09-27 08:54 UTC, predic8 commented on core/src/test/java/com/predic8/membrane/core/lang/spel/functions/BuiltInFunctionsTest.java
> +        exc.getRequest().setBodyContent("{\"name\":\"John\"}".getBytes());
Mutliline String

2024-09-27 08:54 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/flow/ConditionalInterceptor.java
> +    private final SpelParserConfiguration spelConfig = new SpelParserConfiguration(SpelCompilerMode.MIXED, this.getClass().getClassLoader());
Comment why MIXED

2024-09-27 08:54 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/flow/ConditionalInterceptor.java
> +     * SpEL configuration with MIXED mode allows both interpreted and compiled expression evaluation.
Missing: The reason why we used this - Like didn't work with X

2024-09-27 09:02 UTC, predic8 approved these changes

2024-09-27 09:02 UTC, merged