Add OAuth2redirectTest
membrane/api-gateway pull request #1310
Opened 2024-10-17 12:32 UTC by christiangoerdes

2024-10-24 07:33 UTC, christiangoerdes commented on core/src/test/java/com/predic8/membrane/core/interceptor/oauth2/client/b2c/B2CTestConfig.java
> +    public final int clientPort = 2000;
Make this configurable?

2024-10-25 10:58 UTC, rrayst commented
/ok-to-test

2024-10-25 11:53 UTC, rrayst requested changes

2024-10-25 11:53 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/LogHelper.java
> +        if (true) {
please do not commit this

2024-10-25 11:53 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/StateManager.java
> +        Map<String, String> param = URLParamUtil.parseQueryString(URLDecoder.decode(state2, UTF_8), URLParamUtil.DuplicateKeyOrInvalidFormStrategy.ERROR);
just flagging this for later review

2024-10-30 14:03 UTC, predic8 commented on core/src/test/java/com/predic8/membrane/core/OAuth2RedirectTest.java
> +        Rule azureRule = getAzureRule();
inline

2024-10-30 14:03 UTC, predic8 commented on core/src/test/java/com/predic8/membrane/core/OAuth2RedirectTest.java
> +    private static final String CLIENT_URL = "http://localhost:2000";
At begin of class

2024-10-30 14:05 UTC, predic8 commented on core/src/test/java/com/predic8/membrane/core/OAuth2RedirectTest.java
> +        Response clientResponse = step1originalRequest(memCookies);
Extract OAuth2XXXFlowTestClientClass

2024-10-31 08:50 UTC, rrayst approved these changes

2024-11-04 13:50 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/StateManager.java
> +        Map<String, String> param = URLParamUtil.parseQueryString(URLDecoder.decode(state2, UTF_8), URLParamUtil.DuplicateKeyOrInvalidFormStrategy.ERROR);
The `state2` parameter is a value in the `HashMap` created here:

https://github.com/membrane/api-gateway/blob/6cfff97edaa61f20b95cb5b03e219285009cd85c/core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/OAuth2CallbackRequestHandler.java#L83

The getParams() method called there already UTF-8-decodes the values. Is the parameter double-encoded?

2024-11-06 07:00 UTC, t-burch commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/StateManager.java
> +        Map<String, String> param = URLParamUtil.parseQueryString(URLDecoder.decode(state2, UTF_8), URLParamUtil.DuplicateKeyOrInvalidFormStrategy.ERROR);
Yeah without the second decode it ends up still being url encoded

2024-11-07 13:50 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/StateManager.java
> +        Map<String, String> param = URLParamUtil.parseQueryString(URLDecoder.decode(state2, UTF_8), URLParamUtil.DuplicateKeyOrInvalidFormStrategy.ERROR);
added verification that target URL (first request and last) survives potential encodings

2024-11-07 13:51 UTC, rrayst commented on core/src/test/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should probably not be committed. (Removing it myself.)

2024-11-07 13:53 UTC, rrayst approved these changes

2024-11-07 14:11 UTC, rrayst commented
OK, so far. But this introduces adds a failing test to the suite.

Either remove it from the suite or fix the underlying problem.

2024-11-11 10:18 UTC, t-burch commented
/ok-to-test

2024-12-09 16:20 UTC, rrayst requested changes

2024-12-09 16:20 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/interceptor/oauth2client/rf/OAuth2CallbackRequestHandler.java
> +        try (HttpClient hc = new HttpClient()) {
Creating a `HttpClient` here bypasses the rest of the interceptor chain.

2024-12-10 15:42 UTC, t-burch commented
NOT MERGE READY
Tests were expanded to assert that interceptor chain is really continued as expected, not bypassed.
Implementation has to be adjusted

2025-01-14 15:13 UTC, rrayst approved these changes

2025-01-14 15:35 UTC, merged