Javadoc updates
membrane/api-gateway pull request #1340
Opened 2024-11-12 08:50 UTC by t-burch

2024-11-12 08:51 UTC, t-burch commented
Added docs for ApiKeysInterceptor

2024-12-06 15:45 UTC, rrayst commented
/ok-to-test

2024-12-07 18:47 UTC, predic8 requested changes

2024-12-07 18:47 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/apikey/ApiKeysInterceptor.java
> +/**
Instead of proxies use APIs
Can this be rewritten in a more clearer way easier to read for beginners

2024-12-07 18:47 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/apikey/ApiKeysInterceptor.java
> +     */
Controls whether API key validation is enforced or optional. Optional will still load scopes and makes them available in the Exchange property XXXX.

2024-12-07 18:47 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/apikey/stores/ApiKeyFileStore.java
> + */
Add example

2024-12-07 18:47 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/interceptor/apikey/stores/ApiKeyFileStore.java
> +     * @description Path/URL to the api key file.
example

2024-12-16 10:04 UTC, predic8 approved these changes

2024-12-16 10:04 UTC, merged