Rewrite soapproxy validation example
membrane/api-gateway pull request #1383
Opened 2024-12-06 10:48 UTC by t-burch

2024-12-06 18:30 UTC, rrayst commented
/ok-to-test

2024-12-07 18:40 UTC, predic8 requested changes

2024-12-07 18:40 UTC, predic8 commented on distribution/examples/validation/soap-Proxy/README.md
> +    `curl --header "Content-Type: application/soap+xml" -d @city-soap.xml http://localhost:2000/`
-H instead of --header 

http://localhost:2000/city-service

2024-12-07 18:40 UTC, predic8 commented on distribution/examples/validation/soap-Proxy/city-service.wsdl
> +            <s:address location="http://localhost:2001"/>
change location to http://localhost:2001/city-service

2024-12-07 18:40 UTC, predic8 commented on distribution/examples/validation/soap-Proxy/city-soap.xml
> +    <soapenv:Header/>
- Delete Header
- Use s11 as prefix

2024-12-07 18:40 UTC, predic8 commented on distribution/examples/validation/soap-Proxy/invalid-city-soap.xml
> +    <soapenv:Body>
same delete Header and s11

2024-12-07 18:40 UTC, predic8 commented on distribution/src/test/java/com/predic8/membrane/examples/tests/validation/SOAPProxyValidationTest.java
> +			postAndAssert(200, url, CONTENT_TYPE_SOAP_HEADER, readFile("city-soap.xml"));
Use RESTAssured

2024-12-09 15:44 UTC, t-burch commented
Test doesn't work

2024-12-09 15:51 UTC, predic8 approved these changes

2024-12-09 15:51 UTC, merged