Added limit option for amount of mutations in a GraphQL query document
membrane/api-gateway pull request #753
Opened 2023-10-02 08:53 UTC by t-burch

2023-10-02 09:02 UTC, predic8 requested changes

2023-10-02 09:02 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/graphql/GraphQLProtectionInterceptor.java
> +            error(exc, 405, "Too many mutations defined in document.");
I would use 400 Bad Request, 405 if for wrong HTTP Method like POST or GET

2023-10-02 09:02 UTC, predic8 commented on core/src/main/java/com/predic8/membrane/core/graphql/GraphQLProtectionInterceptor.java
> +            if (definition instanceof OperationDefinition)
Can you write this as stream with lambdas? There should also be a test for the count.

2023-10-16 11:54 UTC, rrayst commented on core/src/main/java/com/predic8/membrane/core/graphql/GraphQLProtectionInterceptor.java
> +                .filter(operation -> operation.getOperationType().getOperation().equals("mutation"))
kann `operation.getOperationType().getOperation()` null sein?

2023-10-16 12:00 UTC, t-burch commented on core/src/main/java/com/predic8/membrane/core/graphql/GraphQLProtectionInterceptor.java
> +                .filter(operation -> operation.getOperationType().getOperation().equals("mutation"))
Ohne das hatte es einen null Fehler geworfen

2023-10-25 15:21 UTC, merged