Example for API Key Interceptor (With Conditional Interceptor)
membrane/api-gateway pull request #808
Opened 2024-01-17 14:46 UTC by t-burch

2024-01-17 15:09 UTC, predic8 submitted a review, later dismissed

2024-01-22 11:23 UTC, rrayst requested changes

2024-01-22 11:23 UTC, rrayst commented on distribution/examples/security/api-key/README.md
> +    <keyFileStore location="./demo-keys" />
is there a `.txt` missing?

2024-01-22 11:23 UTC, rrayst commented on distribution/examples/security/api-key/demo-keys.txt
> +# API KEYS FOR DEMONSTRATION PURPOSES ONLY.
superb! please also add this comment in `distribution/conf/keys.txt`.

2024-01-22 11:23 UTC, rrayst commented on distribution/examples/security/basic-auth/simple/README.md
A typo.

2024-01-23 14:24 UTC, rrayst approved these changes

2024-01-23 14:24 UTC, merged