Updated membrane core dependencies in examples to membrane version 5.3.3
membrane/api-gateway pull request #930
Opened 2024-03-05 09:41 UTC by t-burch

2024-03-05 11:20 UTC, rrayst requested changes
can we do this automatically using `ConsistentVersionNumbers`?

2024-03-05 11:29 UTC, t-burch commented
It should already do it, not sure why it does not work

2024-03-06 12:53 UTC, predic8 approved these changes

2024-03-13 19:10 UTC, predic8 approved these changes

2024-03-14 13:29 UTC, christiangoerdes approved these changes

2024-03-14 13:31 UTC, rrayst approved these changes

2024-03-14 13:35 UTC, merged